# Generated by Django 3.1.7 on 2021-12-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
        migrations.RenameField(
            model_name='usergyminfo',
            old_name='classs',
            new_name='className',
        ),
    ]
