# Generated by Django 3.1.7 on 2021-12-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20211219_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='data_end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='data_end',
            new_name='date_end',
        ),
    ]
