# Generated by Django 3.1.7 on 2021-12-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20211220_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userGymInfo',
            new_name='User_Class',
        ),
    ]
